<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::all()->keyBy('slug');

        $products = [
            [
                'category_slug' => 'daging-sapi',
                'name' => 'Daging Sapi Shortplate Slice Premium',
                'slug' => 'daging-sapi-shortplate-slice-premium',
                'types' => ['Frozen', 'Plain', 'Curah'],
                'weight' => '500g',
                'weight_value' => 500,
                'unit' => 'gram',
                'normal_price' => 58000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 1,
                'image' => 'images/prod-beef-slice.jpg',
                'description' => 'Irisan tipis 1.5mm daging sapi impor berlemak gurih, sangat cocok untuk sukiyaki, shabu-shabu, dan grill BBQ rumahan.',
            ],
            [
                'category_slug' => 'ayam-segar',
                'name' => 'Dada Ayam Fillet Boneless Clean',
                'slug' => 'dada-ayam-fillet-boneless-clean',
                'types' => ['Fresh', 'Plain'],
                'weight' => '1000g',
                'weight_value' => 1000,
                'unit' => 'gram',
                'normal_price' => 46000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 2,
                'image' => 'images/cat-ayam.jpg',
                'description' => 'Dada ayam tanpa tulang dan tanpa kulit, tinggi protein dan rendah lemak. Cocok untuk program diet, steak ayam, atau olahan tumis.',
            ],
            [
                'category_slug' => 'ayam-segar',
                'name' => 'Ayam Ungkep Bumbu Kuning Lengkuas',
                'slug' => 'ayam-ungkep-bumbu-kuning-lengkuas',
                'types' => ['Ready to Cook', 'Berbumbu'],
                'weight' => '800g',
                'weight_value' => 800,
                'unit' => 'gram',
                'normal_price' => 42000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 3,
                'image' => 'images/prod-ayam-bumbu.jpg',
                'description' => 'Ayam pejantan utuh potong 4 yang telah diungkep dengan rempah tradisional lengkap. Tinggal goreng atau bakar praktis.',
            ],
            [
                'category_slug' => 'ikan-seafood',
                'name' => 'Fillet Ikan Gurame Segar Bersih',
                'slug' => 'fillet-ikan-gurame-segar-bersih',
                'types' => ['Fresh', 'Plain'],
                'weight' => '500g',
                'weight_value' => 500,
                'unit' => 'gram',
                'normal_price' => 38000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 4,
                'image' => 'images/prod-ikan-gurame.jpg',
                'description' => 'Daging gurame fillet tanpa duri, higienis dan tidak berbau tanah. Siap ditepungi, dibuat sup asam manis, atau asam pedas.',
            ],
            [
                'category_slug' => 'sayuran-siap-olah',
                'name' => 'Paket Sayur Sop Komplit Higienis',
                'slug' => 'paket-sayur-sop-komplit-higienis',
                'types' => ['Ready to Cook', 'Fresh'],
                'weight' => '350g',
                'weight_value' => 350,
                'unit' => 'gram',
                'normal_price' => 12000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 5,
                'image' => 'images/prod-sayur-mix.jpg',
                'description' => 'Kombinasi wortel impor, buncis, kentang, kol, dan seledri yang sudah dicuci bersih dan dipotong rapi. Termasuk bumbu racik.',
            ],
            [
                'category_slug' => 'daging-sapi',
                'name' => 'Daging Sengkel Sapi Potong Rawon / Semur',
                'slug' => 'daging-sengkel-sapi-potong-rawon-semur',
                'types' => ['Fresh', 'Curah'],
                'weight' => '1000g',
                'weight_value' => 1000,
                'unit' => 'gram',
                'normal_price' => 125000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 6,
                'image' => 'images/cat-daging.jpg',
                'description' => 'Daging bagian betis sapi dengan urat kenyal lembut, sangat gurih saat direbus lama untuk masakan rawon, soto, atau semur.',
            ],
            [
                'category_slug' => 'ikan-seafood',
                'name' => 'Ikan Dori Fillet Premium Glazing Rendah',
                'slug' => 'ikan-dori-fillet-premium-glazing-rendah',
                'types' => ['Frozen', 'Plain', 'Curah'],
                'weight' => '1000g',
                'weight_value' => 1000,
                'unit' => 'gram',
                'normal_price' => 48000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 7,
                'image' => 'images/cat-ikan.jpg',
                'description' => 'Daging ikan pangasius putih bersih dengan kadar glazing minimal, tekstur lembut tanpa aroma amis menyengat.',
            ],
            [
                'category_slug' => 'sayuran-siap-olah',
                'name' => 'Paket Sayur Lodeh Racik Bumbu',
                'slug' => 'paket-sayur-lodeh-racik-bumbu',
                'types' => ['Ready to Cook'],
                'weight' => '400g',
                'weight_value' => 400,
                'unit' => 'gram',
                'normal_price' => 14000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 8,
                'image' => 'images/cat-sayur.jpg',
                'description' => 'Paket komplit labu siam, terong ungu, kacang panjang, melinjo, daun melinjo, dan jagung manis siap masak bersama santan.',
            ],
            [
                'category_slug' => 'daging-sapi',
                'name' => 'Daging Giling Sapi Spesial Low Fat',
                'slug' => 'daging-giling-sapi-spesial-low-fat',
                'types' => ['Frozen', 'Plain'],
                'weight' => '500g',
                'weight_value' => 500,
                'unit' => 'gram',
                'normal_price' => 62000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 9,
                'image' => 'images/prod-beef-slice.jpg',
                'description' => 'Daging sapi murni giling dengan rasio lemak kurang dari 10%, cocok untuk pasta bolognese, patty burger, dan bakso rumahan.',
            ],
            [
                'category_slug' => 'ayam-segar',
                'name' => 'Paha Ayam Utuh Marinasi BBQ Smokey',
                'slug' => 'paha-ayam-utuh-marinasi-bbq-smokey',
                'types' => ['Ready to Cook', 'Berbumbu'],
                'weight' => '500g',
                'weight_value' => 500,
                'unit' => 'gram',
                'normal_price' => 36000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 10,
                'image' => 'images/prod-ayam-bumbu.jpg',
                'description' => 'Paha ayam bagian atas dan bawah yang dimarinasi saus barbeque gurih manis dengan aroma asap khas restoran panggang.',
            ],
            [
                'category_slug' => 'ikan-seafood',
                'name' => 'Udang Vaname Kupas Bersih Ekor (PDTO)',
                'slug' => 'udang-vaname-kupas-bersih-ekor-pdto',
                'types' => ['Frozen', 'Plain', 'Fresh'],
                'weight' => '500g',
                'weight_value' => 500,
                'unit' => 'gram',
                'normal_price' => 55000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 11,
                'image' => 'images/hero-2.jpg',
                'description' => 'Udang laut vaname segar ukuran sedang yang sudah dibuang kepala, kulit, dan ususnya, menyisakan ekor rapi.',
            ],
            [
                'category_slug' => 'frozen-food',
                'name' => 'Bakso Sapi Urat Premium 25 Butir',
                'slug' => 'bakso-sapi-urat-premium-25-butir',
                'types' => ['Frozen', 'Curah'],
                'weight' => '500g',
                'weight_value' => 500,
                'unit' => 'gram',
                'normal_price' => 45000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 12,
                'image' => 'images/hero-1.jpg',
                'description' => 'Bakso sapi dengan tekstur urat renyah kenyal dan aroma daging sapi asli tanpa bahan pengawet berbahaya.',
            ],
            [
                'category_slug' => 'daging-sapi',
                'name' => 'Daging Sirloin Steak Cut 200g',
                'slug' => 'daging-sirloin-steak-cut-200g',
                'types' => ['Frozen', 'Plain'],
                'weight' => '200g',
                'weight_value' => 200,
                'unit' => 'gram',
                'normal_price' => 45000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 13,
                'image' => 'images/cat-daging.jpg',
                'description' => 'Potongan steak sirloin dengan strip lemak samping yang juicy, cocok untuk pan-seared steak ala cafe.',
            ],
            [
                'category_slug' => 'ayam-segar',
                'name' => 'Sayap Ayam Broiler Segar (Chicken Wings)',
                'slug' => 'sayap-ayam-broiler-segar-chicken-wings',
                'types' => ['Fresh', 'Plain', 'Curah'],
                'weight' => '1000g',
                'weight_value' => 1000,
                'unit' => 'gram',
                'normal_price' => 38000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 14,
                'image' => 'images/cat-ayam.jpg',
                'description' => 'Sayap ayam utuh isi 10-12 pcs, bersih tanpa bulu, favorit untuk olahan spicy wings atau kaldu sup gurih.',
            ],
            [
                'category_slug' => 'ikan-seafood',
                'name' => 'Cumi Tubuh Ring Calamari Cut',
                'slug' => 'cumi-tubuh-ring-calamari-cut',
                'types' => ['Frozen', 'Plain'],
                'weight' => '500g',
                'weight_value' => 500,
                'unit' => 'gram',
                'normal_price' => 49000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 15,
                'image' => 'images/hero-2.jpg',
                'description' => 'Cumi potong cincin tanpa kulit dan tanpa tinta, siap dimasak tepung goreng krispi atau saus tiram.',
            ],
            [
                'category_slug' => 'sayuran-siap-olah',
                'name' => 'Paket Sayur Asem Komplit Tradisional',
                'slug' => 'paket-sayur-asem-komplit-tradisional',
                'types' => ['Ready to Cook'],
                'weight' => '400g',
                'weight_value' => 400,
                'unit' => 'gram',
                'normal_price' => 12000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 16,
                'image' => 'images/cat-sayur.jpg',
                'description' => 'Paket racik sayur asem siap masak lengkap dengan melinjo, jagung, kacang panjang, labu siam, dan asem jawa.',
            ],
            [
                'category_slug' => 'daging-sapi',
                'name' => 'Daging Iga Sapi Potong Sop / Konro',
                'slug' => 'daging-iga-sapi-potong-sop-konro',
                'types' => ['Fresh', 'Plain', 'Curah'],
                'weight' => '1000g',
                'weight_value' => 1000,
                'unit' => 'gram',
                'normal_price' => 110000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 17,
                'image' => 'images/cat-daging.jpg',
                'description' => 'Potongan iga sapi tebal berdaging gurih, sangat nikmat untuk sop iga bening, iga bakar kecap, atau konro bakar.',
            ],
            [
                'category_slug' => 'ayam-segar',
                'name' => 'Hati Ampela Ayam Bersih 10 Pasang',
                'slug' => 'hati-ampela-ayam-bersih-10-pasang',
                'types' => ['Fresh', 'Plain'],
                'weight' => '500g',
                'weight_value' => 500,
                'unit' => 'gram',
                'normal_price' => 18000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 18,
                'image' => 'images/cat-ayam.jpg',
                'description' => 'Jeroan ati ampela ayam segar yang sudah dicuci bersih dari lemak dan kotoran, siap diungkep atau disambal goreng.',
            ],
            [
                'category_slug' => 'ikan-seafood',
                'name' => 'Fillet Ikan Kakap Merah Segar Beku',
                'slug' => 'fillet-ikan-kakap-merah-segar-beku',
                'types' => ['Frozen', 'Plain'],
                'weight' => '500g',
                'weight_value' => 500,
                'unit' => 'gram',
                'normal_price' => 56000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 19,
                'image' => 'images/hero-2.jpg',
                'description' => 'Daging kakap merah laut kualitas ekspor tanpa duri, sangat lezat untuk menu asam manis, gulai kepala kakap, atau bakar kecap.',
            ],
            [
                'category_slug' => 'sayuran-siap-olah',
                'name' => 'Paket Sayur Capcay Kuah / Goreng',
                'slug' => 'paket-sayur-capcay-kuah-goreng',
                'types' => ['Ready to Cook'],
                'weight' => '350g',
                'weight_value' => 350,
                'unit' => 'gram',
                'normal_price' => 15000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 20,
                'image' => 'images/cat-sayur.jpg',
                'description' => 'Wortel, kembang kol, brokoli, sawi putih, sawi hijau, dan jamur kuping bersih siap tumis.',
            ],
            [
                'category_slug' => 'frozen-food',
                'name' => 'Sosis Sapi Frankfurter Premium 10 Pcs',
                'slug' => 'sosis-sapi-frankfurter-premium-10-pcs',
                'types' => ['Ready to Cook', 'Frozen'],
                'weight' => '500g',
                'weight_value' => 500,
                'unit' => 'gram',
                'normal_price' => 48000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 21,
                'image' => 'images/hero-1.jpg',
                'description' => 'Sosis daging sapi dengan selongsong alami collagen yang renyah saat digigit, aroma smoked beef nikmat.',
            ],
            [
                'category_slug' => 'daging-sapi',
                'name' => 'Daging Sukiyaki Beef Roll 250g',
                'slug' => 'daging-sukiyaki-beef-roll-250g',
                'types' => ['Frozen', 'Plain'],
                'weight' => '250g',
                'weight_value' => 250,
                'unit' => 'gram',
                'normal_price' => 34000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 22,
                'image' => 'images/cat-daging.jpg',
                'description' => 'Gulungan daging sapi slice super tipis untuk menu enoki beef roll, sukiyaki, atau hotpot keluarga.',
            ],
            [
                'category_slug' => 'ayam-segar',
                'name' => 'Ayam Katsu Fillet Breaded Siap Goreng',
                'slug' => 'ayam-katsu-fillet-breaded-siap-goreng',
                'types' => ['Ready to Cook', 'Frozen'],
                'weight' => '500g (4 Pcs)',
                'weight_value' => 500,
                'unit' => 'gram',
                'normal_price' => 39000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 23,
                'image' => 'images/prod-ayam-bumbu.jpg',
                'description' => 'Dada ayam fillet berbalut tepung roti panko renyah, tinggal digoreng 5 menit untuk bekal anak sekolah.',
            ],
            [
                'category_slug' => 'sayuran-siap-olah',
                'name' => 'Baby Buncis Super Organik Petik Segar',
                'slug' => 'baby-buncis-super-organik-petik-segar',
                'types' => ['Fresh', 'Plain'],
                'weight' => '250g',
                'weight_value' => 250,
                'unit' => 'gram',
                'normal_price' => 8000.00,
                'discount_type' => null,
                'discount_value' => null,
                'stock_status' => 'READY_STOCK',
                'is_flash_sale' => false,
                'flash_sale_discount_type' => null,
                'flash_sale_discount_value' => null,
                'flash_sale_sort_order' => 0,
                'is_active' => true,
                'sort_order' => 24,
                'image' => 'images/cat-sayur.jpg',
                'description' => 'Baby buncis muda renyah manis bebas ulat, sudah dipetik ujungnya, siap untuk tumis daging sapi atau telur asin.',
            ],
        ];

        foreach ($products as $p) {
            $catSlug = $p['category_slug'];
            $catId = $categories[$catSlug]->id ?? null;
            if (!$catId) {
                continue;
            }

            unset($p['category_slug']);
            $p['category_id'] = $catId;

            Product::updateOrCreate(
                ['slug' => $p['slug']],
                $p
            );
        }
    }
}
